"""add invoice review fields

Revision ID: d7ef61602818
Revises: f68b5ea2d164
Create Date: 2026-07-14 10:50:28.461813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ef61602818'
down_revision: Union[str, Sequence[str], None] = 'f68b5ea2d164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_invoice_data', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('extracted_invoice_data', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'extracted_invoice_data', 'users', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracted_invoice_data', type_='foreignkey')
    op.drop_column('extracted_invoice_data', 'reviewed_at')
    op.drop_column('extracted_invoice_data', 'reviewed_by_id')
    # ### end Alembic commands ###
